version: '3.8'
services:
  wsapi:
    container_name: wsapi
    build:
      context: .                    # Root of the project
      dockerfile: wsapi.dockerfile  # Dockerfile in the root
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - postgres

  pstatusworker:
    container_name: pstatusworker
    build:
      context: .
      dockerfile: pstatusworker.dockerfile
    depends_on:
      - redis
      - postgres

  roomworker:
    container_name: roomworker
    build:
      context: .
      dockerfile: roomworker.dockerfile
    depends_on:
      - redis
      - postgres

  broadcastworker:
    container_name: broadcastworker
    build:
      context: .
      dockerfile: broadcastworker.dockerfile
    depends_on:
      - redis
      - postgres

  gameworker:
    container_name: gameworker
    build:
      context: .
      dockerfile: gameworker.dockerfile
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: checkersdb
      POSTGRES_DB: checkers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: