services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"    # HTTP (for redirection to HTTPS)
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your NGINX config
      - /home/ec2-user/ssl:/etc/nginx/ssl:ro  # Mount SSL certs
    depends_on:
      - wsapi
    environment:
      - SSL_CERT_PATH=/etc/nginx/ssl/certificate.cert
      - SSL_KEY_PATH=/etc/nginx/ssl/key.pem

  wsapi:
    container_name: wsapi
    build:
      context: .
      dockerfile: wsapi.dockerfile
    expose:
      - "80"  # Expose port 80 internally
    environment:
      - CONFIG_PATH=/root/config/config.json
    depends_on:
      - redis

  pstatusworker:
    container_name: pstatusworker
    build:
      context: .
      dockerfile: pstatusworker.dockerfile
    depends_on:
      - redis

  roomworker:
    container_name: roomworker
    build:
      context: .
      dockerfile: roomworker.dockerfile
    depends_on:
      - redis

  broadcastworker:
    container_name: broadcastworker
    build:
      context: .
      dockerfile: broadcastworker.dockerfile
    depends_on:
      - redis
  
  gameworker:
    container_name: gameworker
    build:
      context: .
      dockerfile: gameworker.dockerfile
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: checkersdb
      POSTGRES_DB: checkers
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data: