# .github/workflows/ecr-push.yml
name: Build and Push All Images to ECR

on:
  workflow_dispatch:
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 923500641637.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build and push all images
        run: |
          ECR_REGISTRY=923500641637.dkr.ecr.eu-central-1.amazonaws.com

          declare -A IMAGES=(
            ["wsapi"]="wsapi.dockerfile"
            ["restapi"]="restapiworker.dockerfile"
            ["pstatus"]="pstatusworker.dockerfile"
            ["room"]="roomworker.dockerfile"
            ["game"]="gameworker.dockerfile"
            ["broadcast"]="broadcastworker.dockerfile"
          )

          for name in "${!IMAGES[@]}"; do
            docker build -f ${IMAGES[$name]} -t $ECR_REGISTRY/$name:latest .
            docker push $ECR_REGISTRY/$name:latest
          done
