# .github/workflows/ecr-push.yml
name: Build and Push All Images to ECR

on:
  workflow_dispatch:
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push all images
        run: |
          ECR_REGISTRY=your-account-id.dkr.ecr.your-region.amazonaws.com

          declare -A IMAGES=(
            ["wsapi"]="wsapi.dockerfile"
            ["restapiworker"]="restapiworker.dockerfile"
            ["pstatusworker"]="pstatusworker.dockerfile"
            ["roomworker"]="roomworker.dockerfile"
            ["gameworker"]="gameworker.dockerfile"
            ["broadcastworker"]="broadcastworker.dockerfile"
          )

          for name in "${!IMAGES[@]}"; do
            docker build -f ${IMAGES[$name]} -t $ECR_REGISTRY/$name .
            docker push $ECR_REGISTRY/$name
          done
